name: Build Android APK

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        
    - name: Change config properties
      run: |
        cd app/src/main/assets
        sed -i 's/app_name=.*/app_name=${{ secrets.APP_NAME }}/' config.properties
        sed -i 's/server_ip=.*/server_ip=${{ secrets.SERVER_IP }}/' config.properties
        sed -i 's/server_port=.*/server_port=${{ secrets.SERVER_PORT }}/' config.properties
        sed -i 's/connection_timeout=.*/connection_timeout=${{ secrets.CONNECTION_TIMEOUT }}/' config.properties
        sed -i 's/read_timeout=.*/read_timeout=${{ secrets.READ_TIMEOUT }}/' config.properties
        
    - name: Build APK
      run: |
        cd app
        gradle assembleDebug --warning-mode none
        
       - name: Check if APK exists
  run: |
    cd app
    ls -la build/outputs/apk/debug/ || echo "APK not found" 
        
        
        
        
    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: app-debug
        path: app/build/outputs/apk/debug/app-debug.apk